### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by eidoHA** [KevinBonnoron/the_keys#1]
Thanks for this integration, this could be a life saver to finaly use my door lock in HA.
Im a nuby in HA

after adding this repository in HACS and downloading it, files goes to custom_components/the_keys (not KevinBonnoron/the_keys)
did Restart and did find the integration but came this error.

Erreur
Le flux de configuration n'a pas pu être chargé: {"message":"Invalid handler specified"}

help?

**Comment by KevinBonnoron** [comment]
Hello

I am a bit surprised you found this integration since i didn't finished the hacs migration. May i ask you how did you found it?

I will take a look at your problem.

**Comment by eidoHA** [comment]
Hi, just did a web search thekeys home assistant.

Let me know if you need more info. Thanks

Le lun. 24 juil. 2023 à 09:15, Kevin Bonnoron ***@***.***> a
écrit :

**Comment by KevinBonnoron** [comment]
BTW you need to add the the country code in front of your phone number with a "+" instead of 0 when configurating the keys in the integrations page.
example for France: 01 23 45 67 89 -> +331 23 45 67 89

**Comment by eidoHA** [comment]
On the The keys app? Yes, it's already like this.

Le dim. 30 juil. 2023, 09:52, Kevin Bonnoron ***@***.***> a
écrit :

**Comment by KevinBonnoron** [comment]
I tryed this morning and I don't get any error. No device is coming though, i will to investigate on this. By any chance did you have bough the [gateway](https://www.the-keys.eu/en/accessories/11-gateway.html)?

If you don't have it, it will not work sadly :(. They didn't opened the bluetooth protocol (for security reasons i suppose) so i can't control the lock directly.

**Comment by eidoHA** [comment]
Yes I have the gateway

Le mar. 1 août 2023, 10:33, Kevin Bonnoron ***@***.***> a
écrit :

**Comment by KevinBonnoron** [comment]
Strange. You should see the configuration screen. Do you have something in the logs?

**Comment by KevinBonnoron** [comment]
I made a change in the lib used in the back by this repo to get infos from the locks but i am not able to test it right now. Maybe that will fix your issue.

I am not sure it will appear as an update in HACS (i never really completed the required configuration). If not you may have to uninstall the integration, remove and add again the repository and then install the integration

**Comment by eidoHA** [comment]
Ok, i will try it on my return from holiday. Thanks

Le jeu. 3 août 2023, 08:33, Kevin Bonnoron ***@***.***> a
écrit :

**Comment by eidoHA** [comment]
hi, did what you told me: manual uninstall and reinstall by adding repository, then i started the integration. All fine, it asked the user (+33**...) and password. after conclusion, the integration shows 'configuration fail' (in french).

Logger: homeassistant.config_entries
Source: custom_components/the_keys/__init__.py:19

Error setting up entry +33******** for the_keys
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/the_keys/__init__.py", line 19, in async_setup_entry
    hass.data[DOMAIN] = await hass.async_add_executor_job(api.get_devices)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/the_keyspy/api.py", line 93, in get_devices
    partages_accessoire = self.find_partage_by_lock_id(serrure.id).partages_accessoire
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/the_keyspy/api.py", line 40, in find_partage_by_lock_id
    return Partage.from_dict(self.__http_get(f"partage/all/serrure/{lock_id}")["data"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/api.py", line 72, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 201, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 263, in _decode_generic
    res = _get_type_cons(type_)(xs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 317, in <genexpr>
    items = (_decode_dataclass(type_arg, x, infer_missing)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 159, in _decode_dataclass
    field_value = kvs[field.name]
                  ~~~^^^^^^^^^^^^
KeyError: 'remote_key_sharing_id'

**Comment by KevinBonnoron** [comment]
It seems thekeys did some changes in their apis. I found a lot of bug but finally managed to fix the issue. You should have an update of the package in hacs. If not uninstall / reinstall should do the trick.

Hope this time it will work

**Comment by eidoHA** [comment]
Sorry, still error

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/the_keys/__init__.py", line 19, in async_setup_entry
    hass.data[DOMAIN] = await hass.async_add_executor_job(api.get_devices)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/the_keyspy/api.py", line 93, in get_devices
    partages_accessoire = self.find_partage_by_lock_id(serrure.id).partages_accessoire
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/the_keyspy/api.py", line 40, in find_partage_by_lock_id
    return Partage.from_dict(self.__http_get(f"partage/all/serrure/{lock_id}")["data"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/api.py", line 72, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 201, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 263, in _decode_generic
    res = _get_type_cons(type_)(xs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 317, in <genexpr>
    items = (_decode_dataclass(type_arg, x, infer_missing)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 197, in _decode_dataclass
    value = _decode_dataclass(field_type, field_value,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 159, in _decode_dataclass
    field_value = kvs[field.name]
                  ~~~^^^^^^^^^^^^
KeyError: 'telephone'

**Comment by KevinBonnoron** [comment]
Strange. It seems that your user share does not contains any phone number.

Could you please log in to the-keys api here : https://api.the-keys.fr/ with you phone number & password.
You should see a page with all your lockers, click on the gear and go to "View". In the new page go to "Shares" tab, here you should see all shares you've done for this lock. By default the-keys create a default user share for you.

If you see the user share click on the gear and "View" and check that your share name also contains your phone number? Don't post any capture here, those are private infos
Thanks

**Comment by eidoHA** [comment]
there is:
ID  xxxx
...
Name   ___ _____
User   same name and (phone number +33...)
Locker   xxxx
notification ...

**Comment by KevinBonnoron** [comment]
Very strange. I tried another fix you should see soon in hacs. Tell me if you've got any other issue

**Comment by eidoHA** [comment]
yeah, still:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/the_keys/__init__.py", line 19, in async_setup_entry
    hass.data[DOMAIN] = await hass.async_add_executor_job(api.get_devices)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/the_keyspy/api.py", line 93, in get_devices
    partages_accessoire = self.find_partage_by_lock_id(serrure.id).partages_accessoire
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/the_keyspy/api.py", line 40, in find_partage_by_lock_id
    return Partage.from_dict(self.__http_get(f"partage/all/serrure/{lock_id}")["data"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/api.py", line 72, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 201, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 263, in _decode_generic
    res = _get_type_cons(type_)(xs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 317, in <genexpr>
    items = (_decode_dataclass(type_arg, x, infer_missing)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 197, in _decode_dataclass
    value = _decode_dataclass(field_type, field_value,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dataclasses_json/core.py", line 159, in _decode_dataclass
    field_value = kvs[field.name]
                  ~~~^^^^^^^^^^^^
KeyError: 'telephone'

**Comment by KevinBonnoron** [comment]
OK i pushed a new fix. I checked when "telephone" field was missing from the api, with the old code i also got the "KeyError: 'telephone'", with the new one it's working. COuld you update the package in hacs, restart home assistant and test again please?

**Comment by eidoHA** [comment]
CA MARCHE!!!! your my hero! Merci beaucoup. Ive got to buy you a drink.

**Comment by KevinBonnoron** [comment]
There is still an issue with the current status of the lock, especially when you lock / unlock manually. But i will open another issue for this point.
Thank you for your feedback, patience and time.
